lebed_guestbook_homepage:
    pattern:  /
    defaults: { _controller: LebedGuestbookBundle:Default:index }
lebed_guestbook_viewMessages:
    pattern: /viewMessages
    defaults: { _controller: LebedGuestbookBundle:Default:viewMessages }
lebed_guestbook_search:
    pattern: /search
    defaults: { _controller: LebedGuestbookBundle:Default:search}